---
title: Josiah Wiebe
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  work:
    title: Work
    output: false
email: hi@jwie.be
description: Josiah is a designer & developer based in the Canadian Prairies. He is
  passionate about Javascript development and the great outdoors. Most of his work
  is done through Collectif.
baseurl: 
url: https://jwie.be
twitter_username: josiahwiebe
github_username: josiahwiebe
instagram_username: josiahwiebe
spotify_username: josiahwiebe
exclude:
- "/node_modules/"
- "**.sublime-project"
- "**.sublime-workspace"
- gulpfile.js
- package.json
- ".git"
- README.md
markdown: kramdown
